### ISSUE TITLE
A cache with identifier "azurestorage" does not exist. in install tool v8.7

### ISSUE THREAD

**Issue by tmotyl** [macopedia/typo3-azurestorage#15]
After upgrade to 8.7 
I'm getting "A cache with identifier "azurestorage" does not exist." error in install tool upgrade wizards.
The filelist module works without issues.

**Comment by benjaminhirsch** [comment]
Hmm that would mean that there is no cache with that identifier, but how is that possible? Could you please investigate a little bit further to get more information? I have this extension running on multiple sites running 8.7 withtout any problems so far. :

**Comment by tmotyl** [comment]
Hi @benjaminhirsch,
This is indeed quite strange. I managed to run update wizards through typo3 console and the problem is now solved.
