### ISSUE TITLE
New tag and TER release

### ISSUE THREAD

**Issue by tmotyl** [macopedia/typo3-azurestorage#28]
Hi
Can you please tag a new version as well as relase to TER?
The current version in TER is 0.3.4, which results in showing the extension as outdated:
![image](https://user-images.githubusercontent.com/515397/100600701-ec74e600-3301-11eb-8909-268872b5c692.png)

**Comment by benjaminhirsch** [comment]
Hey @tmotyl, thanks for reaching out. Unfortunatley, I have to tell you, that I'm no longer going to support non composer based installations of TYPO3, therefore I won't release a new Version on TER in the future, only packagist.org.

Unfortunaltley, my time is at the moment really limited and therefore  - if you have time and are in need of a new version, a pull request with the necessary additions would be apreciated.

**Comment by tmotyl** [comment]
Hi @benjaminhirsch 
My main concern is the fact that TER is not only used to download extensions for non-composer mode, but also as a single place to discover extensions/packages. If extension is not visible there, it will not be found and used. 
I see a grate benefit in having the extension being up to date in TER even if non-composer mode is not supported.

Since recently it's also possible to automatically push new releases to TER using github actions and the new TER REST API
https://github.com/TYPO3/tailor

Right now I'm using the dev-master version of this extension in the project, as the most recent commits from master hasn't been released yet.
It woudl be grateful for a release :)

**Comment by tmotyl** [comment]
@benjaminhirsch AFAIK it's enough to merge https://github.com/benjaminhirsch/typo3-azurestorage/pull/29 and release a new tag

**Comment by benjaminhirsch** [comment]
Released 0.5.3
