### ISSUE TITLE
TYPO3 12.x not working

### ISSUE THREAD

**Issue by weisgerberm** [macopedia/typo3-azurestorage#39]
Hi, I just wanted to test the extension, but with TYPO3 12 it does not work yet, because it checks for the constant TYPO3_MODE in files. So you end up in the die("ACCESS DENIED")
Could you please fix this?

**Comment by tmotyl** [comment]
can you provide a PR? I can merge it then quickly

**Comment by tmotyl** [comment]
fixed in https://github.com/macopedia/typo3-azurestorage/releases/tag/v1.0.0
