### ISSUE TITLE
Pagination on ListView

### ISSUE THREAD

**Issue by zbychu555** [macopedia/typo3-azurestorage#9]
Is it possible to enable pagination on ListView? When I have more than ~50 images - opening a folders takes a lot of time and sometimes I get timeouts.

**Comment by benjaminhirsch** [comment]
Hm this shouldn't be part of the driver itself, I guess this is handled by the FAL. The driver is build against the the AbstractHierarchicalFilesystemDriver which doesn't offer any possibility to do something with paging. Normally this should work. I will have a look into it anyway! :)

**Comment by benjaminhirsch** [comment]
I guess I've found a solution to speed thinks up! Currently I'm fetching the complete blob, even for lookups. I will change this behaviour in the next update, that only the meta data is fetched! I think this will speed up thinks massively - at least  I hope so 😄

**Comment by zbychu555** [comment]
Thank you! Will be great!

**Comment by benjaminhirsch** [comment]
I'm working on a new release, hopefully I will bring it online later this day. I was able to achieve a good increase performance wise and paging should also work then. 😃

**Comment by benjaminhirsch** [comment]
@zbychu555 please ty out Version 0.3.1 and let me know if It's better now! :)

**Comment by zbychu555** [comment]
Wow! Thank you for really fast and good job! When I open folder first time it's still long time, but pagination works great (so time is shorter than before:)) 
But what can I see, there are no folders in ListView in right area, I can see only images.

**Comment by benjaminhirsch** [comment]
Hi @zbychu555, sorry for the late response. Do you still have the problem? Unfortunatley I'm not able to reproduce this Problem. 😕

**Comment by benjaminhirsch** [comment]
I've found the problem, it's related to the _processed_ folder and the limit of 5.000 files per call to the storage API. I will investigate the problem.

**Comment by benjaminhirsch** [comment]
Version 0.3.3 partially fixes the problem I guess - please have a look at the patch notes for detailed Informationen regarding this issue. :-)

**Comment by zbychu555** [comment]
Hi, sorry for really long silence from my side... I can see 'folders in folder' but not main folders which are in my root. But it's not big issue in my opinion :)

**Comment by benjaminhirsch** [comment]
Just to be clear about that. With you can't see folders inside your root folder, means you can't see the folders "Documents", "Images" and "user_upload" like in the example?

![image](https://user-images.githubusercontent.com/2293943/28733143-0d8879f4-73db-11e7-9c83-3f2df200c0f1.png)

**Comment by zbychu555** [comment]
Yes, I cannot see this folders. 
<img width="721" alt="azure" src="https://user-images.githubusercontent.com/4426885/28733382-260a9178-73dc-11e7-91dc-eb190e45acbb.png">

**Comment by benjaminhirsch** [comment]
Since which version do you use the extension? I'm asking, because in one of the first versions, there was a change which had impact on the file/folderidentifier hash.

**Comment by zbychu555** [comment]
I have the latest master commit (b36023e). This is strange because I see that it works for you :)

**Comment by zbychu555** [comment]
As I remember it was my pull request which changed hashes:) I think it's no a problem for me, because I started using Azure after this change. I checked and new folders also doesn't work.

**Comment by benjaminhirsch** [comment]
Hmmm :confused:  ... I'm sorry, for the moment, I've no idea.

**Comment by zbychu555** [comment]
Thanks a lot for your work on this issue. I'm so happy that pagination works - missing 'root' folders in my installation don't be a big issue in this case :)
